<?php

return [

    'REGISTER_SUCCESS' => 'You have registered successfully.',
    'EMAIL_ALLREADY_EXIST' => 'This email already exist.',
    'INVALID_CREDENTIAL' => 'Invalid Email or Password.',
    'LOGIN_ERROR' => 'Please provide atlest one id facebook or google.',
    'LOGOUT_SUCCESS' => 'User logged out successfully.',
    'LOGOUT_ERROR' => 'Sorry, the user cannot be logged out.',
    'SEARCH_KEYWORD_NOT_PROVIDED' => 'Please provide keyword to search people.',
    'SEARCH_RESULT_NOT_FOUND' => 'No result found for this keyword.',
    'USER_NOT_EXIST' => 'User does not exist.',
    'USER_FOLLOW_SUCCESS' => 'User followed successfully.',
    'USER_STATUS_SUCCESS' => 'User Updated successfully.',
    'USER_UNFOLLOW_SUCCESS' => 'User unfollowed successfully.',
    'ALL_FIELDS_MANDATORY' => 'All fields are mandatory.',
    'FILE_TYPE_NOT_ALLOWED' => 'File type not allowed. only image and video file allowed.',
    'FILE_UPLOADED_SUCCESS' => 'File uploaded successfully.',
    'PARAMETER_MISSING' => 'Parameter missing or invalid.',
    'ALBUM_ALREADY_EXIST' => 'Album with this name already created.',
    'ALBUM_SAVED_SUCCESS' => 'Album saved successfully.',
    'ALBUM_DISCARDED' => 'Album discarded successfully.',
    'NO_ALBUM_FOUND' => 'No Album found.',
    'ALBUM_LIST' => 'Album list.',
    'ALBUM_UPDATED' => 'Album updated successfully.',
    'SOMETHING_WENT_WRONG' => 'Something went wrong on Server. Please try again.',
    'ALBUM_DELETED' => 'Album deleted successfully.',
    'PROFILE_PIC_CHANGED_SUCCESS' => 'Profile pic updated successfully.',
    'STORY_SAVED_SUCCESS' => 'Stories saved successfully.',
    'STORY_DUPLICATE' => 'You have already created same story.please enter another.',
    'GET_STORIES' => 'All Stories.',
    'GET_ERROR' => 'Oops Something went wrong!.',
    'ACCEPT_REQUEST' => 'You have Succesfully Accepted.',
    'REJECT_REQUEST' => 'You have Succesfully Rejected.',
    'NEWSFEED'=>'Record Added Successfully',
    'GETFEED'=>'News record found successfully'
];
